export const heroFields = {
  "SingleDisplay": [
    "breadCrumb",
    "heading",
    "richDescription",
    "buttons",
    "bgImage",
    "showDropdown",
    "showBreadcrumbs",
    "dropdownList",
    "isLightMode",
    "isBgImageEffect"
  ],
  "SingleGeneric": [
    "breadCrumb",
    "heading",
    "richDescription",
    "buttons",
    "bgImage",
    "showDropdown",
    "showBreadcrumbs",
    "dropdownList",
    "isLightMode",
    "isBgImageEffect"
  ],
  "SingleBGColour": [
    "breadCrumb",
    "heading",
    "richDescription",
    "buttons",
    "htmlAttr",
    "showDropdown",
    "showBreadcrumbs",
    "dropdownList",
    "isLightMode",
   ],
  "SingleLower": [
    "breadCrumb",
    "heading",
    "richDescription",
    "buttons",
    "bgImage",
    "showDropdown",
    "showBreadcrumbs",
    "dropdownList",
    "isBgImageEffect",
    "isLightMode",
   ],
  "SingleDynamic": [
    "breadCrumb",
    "heading",
    "dynamicRichText",
    "buttons",
    "dynamicImages",
    "showBreadcrumbs",
    "isLightMode",
    ],
  "Twocolumn - Primary": [
    "breadCrumb",
    "heading",
    "richDescription",
    "logo",
    "buttons",
    "bgImage",
    "showDropdown",
    "showBreadcrumbs",
    "dropdownList",
    "isLightMode",
   ],
  "Twocolumn - Secondary": [
    "breadCrumb",
    "heading",
    "richDescription",
    "buttons",
    "bgImage",
    "showDropdown",
    "showBreadcrumbs",
    "dropdownList",
    "isLightMode",
  ],
  "Twocolumn - Tertiary": [
    "breadCrumb",
    "heading",
    "richDescription",
    "buttons",
    "bgImage",
    "showDropdown",
    "showBreadcrumbs",
    "dropdownList",
    "isLightMode",
  ],
  "CustomerStories": [
    "breadCrumb",
    "heading",
    "richDescription",
    "buttons",
    "logo",
    "menuList",
    "showBreadcrumbs",
    "isLightMode",
  ],
  "InsightArticle": [
    "breadCrumb",
    "heading",
    "richDescription",
    "bgImage",
    "showBreadcrumbs",
    "isLightMode"
  ],
  "InsightsGeneric": [
    "breadCrumb",
    "heading",
    "richDescription",
    "insightsCarouselData",
    "subHeading",
    "insightsCard",
    "showBreadcrumbs",
    "isLightMode"
  ],
  "Person": [
    "breadCrumb",
    "heading",
    "richDescription",
    "bgImage",
    "htmlAttr",
    "showBreadcrumbs",
    "isLightMode",
  ],
  "Dropdown": [
    "dropdownList",
    "heading",
    "richDescription",
    "buttons",
    "bgImage",
    "isLightMode",
    ]
}
