export const notificationFields = {
  Small: [
    'backgroundColor',
    'categoriesPage',
    'cta',
    'description',
    'isGlobal',
    'isEnabled',
    'SpecificPage',
    'isPersistent',
  ],
  Medium: [
    'heading',
    'backgroundColor',
    'categoriesPage',
    'cta',
    'description',
    'isGlobal',
    'isEnabled',
    'SpecificPage',
    'isPersistent',
  ],
  Carousels: ['carouselData'],
  ToastSpinner: ['toastMessage', 'isPersistent', 'autoHide'],
  ToastSuccess: ['toastMessage', 'isPersistent', 'autoHide'],
  ToastWarning: ['toastMessage', 'isPersistent', 'autoHide'],
  ToastError: ['toastMessage', 'isPersistent', 'autoHide'],
  ToastInfo: ['toastMessage', 'isPersistent', 'autoHide'],
}
